version: '3'
services:
        web:
                image: snake_realgame_v1
                build: .
                ports:
                        - "8344:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped