version: '3'
services:
        web:
                image: snake_realgame_web_v1
                build: .
                ports:
                        - "7495:7495"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped